version: '3.9'
services:
    node_srv:
        build:
            context: ..
            dockerfile: Docker.stuff/node.dockerfile
        image: node_srv
        environment:
            - REACT_APP_HOST=0.0.0.0
        container_name: 'node_srv'
        networks:
            - storemon
        ports:
            - 3000:3000
    mysql:
        container_name: db_server
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: tempPass
            MYSQL_DATABASE: storemon
            MYSQL_USER: storemon
            MYSQL_PASSWORD: storemon1234
        volumes:
            - dbData:/var/lib/mysql
        networks:
            - storemon        
    restapi:
        build:
            context: .
            dockerfile: drf.dockerfile
        image: restapi
        container_name: 'restapi'
        networks:
            - storemon
        depends_on:
            - mysql
        ports:
            - 8000:8000
volumes: 
    dbData:

networks:
    storemon:
